### ISSUE TITLE
Backpacks lose all contents on death with Allure gravestones enabled

### ISSUE THREAD

**Issue by sableseyler** [TerraformersMC/Campanion#102]
With Allure enabled, and while wearing a backpack, if I die, the contents of the backpack vanish entirely. They are not displaced into the gravestone inventory (thus recovered or scattered as capacity allows when I break it), nor do they stay in the backpack, nor are they scattered immediately onto the ground. I'll gladly dig in and fetch any logs that would be helpful for y'all on this. Let me know what I can do to help.

**Comment by superon** [comment]
seems they just vanish, nothing to do with allure gravestones

**Comment by Prospector** [comment]
Unfortunately there's not much I can do about Allure gravestones. The mod does not appear to be open source. However, in the latest version there is now compatibility with the Gravestones mod, so you can use that as an alternative: https://www.curseforge.com/minecraft/mc-mods/gravestones
