### ISSUE TITLE
Game crashes after crafting tent bag

### ISSUE THREAD

**Issue by Infagoose51** [TerraformersMC/Campanion#105]
Crafted a tent bag with a large tent, as soon as I tried to put it in my inventory the game crashed and I can't join the world any more. Playing on a server with others, they have no problem joining.

**Comment by coderbot16** [comment]
Can you send a crash report please?

**Comment by Infagoose51** [comment]
Read other comments about incompatibility with Optifabric, which we are running. Thanks

**Comment by coderbot16** [comment]
Yeah, unfortunately we do some fancy tendering that makes us incompatible. It could be good for us to indicate this more explicitly, however.
