### ISSUE TITLE
Cannot Place Tents At All

### ISSUE THREAD

**Issue by Okay777** [TerraformersMC/Campanion#106]
I am using "v1.3.1 for 1.16.4" and I cannot place a tent. I did everything the wiki says to do, but the so called "schematic" or outline of the tent before you place it does not show up. And for that I cannot place a tent! The rest of the mod works perfectly fine as well.

**Comment by Prospector** [comment]
You probably never combined the tent with a tent bag in a crafting table, you need to do that in order to place it for now.

**Comment by Prospector** [comment]
As of v1.3.3, you should be able to place tents directly, even if they're not in a bag
