### ISSUE TITLE
Campanion server error when joining vanilla server

### ISSUE THREAD

**Issue by SirOMGitsYOU** [TerraformersMC/Campanion#109]
Launched up with my mods + identity joined my network lobby which has a vanilla papermc hub server. I really want to include campanion in my modpack but if it can't work with my vanilla lobby I'm afraid it may have to be dropped, if you could do anything to work around this that would be fantastic.

[latest.log](https://github.com/TerraformersMC/Campanion/files/5860910/latest.log)

**Comment by Prospector** [comment]
I don't see campanion referenced in your log at all, is it even installed? I also don't see any errors in there.

**Comment by SirOMGitsYOU** [comment]
> I don't see campanion referenced in your log at all, is it even installed? I also don't see any errors in there.

it is installed, I just had the same issue with Identity, the guy said that because it's required on server and client-side this is why it generates this issue.

**Comment by Prospector** [comment]
Well Campanion *is* required on both server and client. I still don't understand what the "server error" is?

**Comment by SirOMGitsYOU** [comment]
> Well Campanion _is_ required on both server and client. I still don't understand what the "server error" is?

the server is rejecting the client connecting with campanion because its not installed on the server, i assume it's not possible to get it to work without this? even in this scenario.

**Comment by Prospector** [comment]
Nothing I can really do without a specific error or something. That log you posted also definitely doesn't have campanion installed, so not sure if you uploaded the wrong file or what? I don't really see why you couldn't join a papermc server with the mod, but why exactly *are* you joining a server without the mod with the mod installed on your client?
