### ISSUE TITLE
[Wiki] Link in the wiki Home for Grapling Hooks is broken

### ISSUE THREAD

**Issue by Levoment** [TerraformersMC/Campanion#11]
Hi

The link in the **Home** wiki (https://github.com/TerraformersMC/Campanion/wiki) for **Grappling Hooks** leads to **https://github.com/TerraformersMC/Campanion/wiki/Grappling-Hooks**, but the actual page containing the Grapling Hooks information is **https://github.com/TerraformersMC/Campanion/wiki/Grappling-Hook**

- Broken Link: &nbsp;&nbsp;https://github.com/TerraformersMC/Campanion/wiki/Grappling-Hooks
- Working Link: https://github.com/TerraformersMC/Campanion/wiki/Grappling-Hook

**Comment by NeusFear** [comment]
Thanks so much for letting me know, I updated it.
