### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by FineExcuse** [TerraformersMC/Campanion#113]
after placing down a rope bridge and setting it up _the bridge is invisible_ , you may walk on it, see it's hit box or break it, but it doesnt appear, and from videos I've seen on YouTube this is just for me so if you could explain to me if I am missing something please reach out

**Comment by NeusFear** [comment]
I’ll take a guess that you have either optifabric or sodium installed. They both don’t work with fabric rendering api.
