### ISSUE TITLE
Rope bridge does not rotate and resulting bridge has no collision

### ISSUE THREAD

**Issue by pbaja** [TerraformersMC/Campanion#115]
![2021-02-19_20 12 22](https://user-images.githubusercontent.com/3957419/108550555-01548a80-72ef-11eb-83fd-bd63d4c583be.png)
After placing both Rope Bridge Posts and connecting them with Rope, the posts do not rotate to match bridge direction. Also, the bridge has no collision, but the incorrectly placed posts do.

This is all while being connected to a standalone server.  **Everything works correctly on single player**.
There are no messages in the logs both on server and on client.
Restarting client and/or server does not change anything.
Installed Campanion version : 1.3.4

List of installed mods:
```
Fabric API
ClothConfig
Fabric Kotlin
Trinkets
Patchouli
Architectury API
Reborn Core
Mod Menu
Auto Config API
Textile Backup
Canvas Renderer
Phosphor
Lithium
Cull Particles Fabric
Xaero's Minimap
Xaero's World Map
Roughly Enough Items
Roughly Enough Resources
Inventory Profiles
SimpleHarvest
Light Overlay
FallingTree
Hwyla
AppleSkin
Enchantment Descriptions
Beenfo
Better Signs and Frames
Spark
Expanded Storage
Compressed Blocks
Dank Storage
Improved Stations
Adorn
Extra Alchemy
Fabric Waystones
Fabric Furnaces
Glassential
Oh The Biomes You'll Go
Vanilla Hammers
AdventureZ
Allure
Mo' Structures
Astromine: Complete
BetterNether
Modern Glass Doors
Campanion
TechReborn
Give Me Hats
Consistency+
Charm
Charmonium
Ducts
Magnet for Fabric
Blur
Diagonal Panes
Identity
Better Dropped Items
Snowdrift
LambDynamicLights
Illuminations
Better Flora
Dark Paintings
Advancements Enlarger
Dark Loading Screen
```

**Comment by NeusFear** [comment]
Does this happen on the latest version? v1.3.5

**Comment by pbaja** [comment]
I just tested it and it works great on v1.3.5 both on multiplayer and singleplayer.
Awesome! Thank you.
