### ISSUE TITLE
Rope bridge doesn't render but has collision and bounding box

### ISSUE THREAD

**Issue by amscrw** [TerraformersMC/Campanion#116]
I placed the posts and they were completely invisible but i could still interact with them and form a bridge between two placed (still invisible) posts. The resulting bridge was also completely invisible but functional. I'm running the mod on Windows 10, Fabric 1.16.5, with Sodium (tested all rendering methods available to me), Phosphur and Lithium as the only performance mods. I've tried running the mod on its own without any other mods and the same thing happened; invisible, yet functional bridge. Everything else renders correctly except for the bridge.

**Comment by pbaja** [comment]
The mod does not work with Sodium because Sodium replaces and is incompatible with Fabric Rendering API.
You have to wait for Sodium to support it or remove Sodium (I replaced sodium with Canvas renderer in my game)

**Comment by Prospector** [comment]
Yeah, Sodium doesn't support the Fabric renderer API right now
