### ISSUE TITLE
Player can get many Rope Ladders from using only 1 Rope Ladder

### ISSUE THREAD

**Issue by Levoment** [TerraformersMC/Campanion#12]
If you go up more than 64 blocks high and place a single rope ladder, it will go all the way down until another block is met. Then, when one breaks the base of the rope ladder, the player gets back as many rope ladders were needed to meet the block at the bottom.

I am using

Minecraft: 1.15.2
Fabric Loader: 0.8.2+build.194
Fabirc Api: 0.5.1+build.294-1.15
Campanion: 1.0.8+build.7

And around 64 more mods. I'm not sure if  other mods might be causing this.

**Comment by NeusFear** [comment]
I'll work on a fix for this now.

**Comment by NeusFear** [comment]
1.0.9 should be approved on curseforge shortly

**Comment by Levoment** [comment]
Wow, that was fast. :)

**Comment by Levoment** [comment]
I don't mean to be a bother, but there is another problem now. After the fix.

When putting the Ladder, it only uses the stack that was used by the player with right click. If the player has more Rope Ladders on the inventory, it doesn't use them. That means that if the player uses a stack of Ladder Rope of quantity 2, but it has another stack on the inventory of 64 Ladder Ropes, only 2 will be put so the ladder doesn't go all the way down.

It doesn't bother me, since it can be worked around by going down the ladder and putting more Rope Ladders manually, but I thought I might mention it.
