### ISSUE TITLE
Campanion will fully work if both Soduim and Indium are installed

### ISSUE THREAD

**Issue by nullified33** [TerraformersMC/Campanion#121]
https://github.com/comp500/Indium

**Comment by Prospector** [comment]
Yeah, and when Sodium eventually natively supports the fabric renderer api it will also fully work.

**Comment by nullified33** [comment]
> Yeah, and when Sodium eventually natively supports the fabric renderer api it will also fully work.

 In the Campanion page you should probably add that piece of info.

**Comment by Prospector** [comment]
Indium isn't release software and doesn't even have any builds publicly available, so I won't be pointing users to install it at this time
