### ISSUE TITLE
Items duplicate when trying to craft a filled tent bag

### ISSUE THREAD

**Issue by DanDragonWolf** [TerraformersMC/Campanion#13]
When I try to craft together an empty tent bag and a tent, it doesn't work and when I move the items out of the crafting table they duplicate. This also happens in my inventory crafting. I am using the 1.16 snapshot version that is on curseforge.

**Comment by Wyn-Price** [comment]
This no longer seems to be a bug
![TrFYq8B5Wa](https://user-images.githubusercontent.com/15876682/86168269-e0e18100-bb0f-11ea-8064-73585007a560.gif)
