### ISSUE TITLE
Rope bridge invisible when placed

### ISSUE THREAD

**Issue by TinyBoxer86** [TerraformersMC/Campanion#145]
Whenever I try to place a rope bridge post, it's invisible except for the block highlight. It has collision and I can break it to retrieve the item, I just can't see it. I have quite a lengthy mod list, but can list them if needed. Thank you in advance!
![Screenshot (183)](https://user-images.githubusercontent.com/86693098/126189000-ec3a1aad-15cf-4775-8934-a07eefbdb86e.png)

**Comment by Wyn-Price** [comment]
The fabric rendering api (which the bridges use) does not work with optifine or sodium. Do you have any of those installed?

**Comment by TinyBoxer86** [comment]
> 
> 
> The fabric rendering api (which the bridges use) does not work with optifine or sodium. Do you have any of those installed?

Oh, I see! I do have sodium installed, so that's totally the issue. Thanks for your answer! :)
