### ISSUE TITLE
[BUG] Tent Doesn't Reorient Some Horizontally-Orientated Blocks

### ISSUE THREAD

**Issue by Xechorizo** [TerraformersMC/Campanion#148]
**Is this a modpack or mod issue?**
(if something is screwy using a certain mod, then send the bug to the mod dev first.)

- Mod Suspected - Campanion Tents seem to work well until paired with oriented blocks. If Tent cannot manage blocks that write world data, possibly a check can be done to prevent packing the Tent, or skip world data blocks within the Tent upon packing.

**PLEASE MENTION IF YOU ADDED ANY MODS.. ESPECIALLY SODIUM, IF YOU DON'T, IT MAKES US VERY GRUMPY**

- None

**Modpack Version**
(any bugs using a non-up-to-date version will be asked to replicate with the most up-to-date release)

- All of Fabric 3 v2.8.5

**Describe the bug**

- Picking up a Campanion Tent with a Campanion Tent Bag, rotating the tent, and placing the tent again, places blocks with old orientations. This causes some placed blocks within the tent to be misoriented. For example:

1. Kibe Xp Shower, Placer, Breaker
2. AE2 Terminals, P2P Tunnels
3. Industrial Revolution Power Cables
4. Chisels & Bits

**To Reproduce**

- Place an affected horizontally-oriented block in range or within a Campanion 1.3.5 Tent.
- Pick up the Tent with the Tent Bag.
- Rotate the Tent.
- Place the Tent.
- Observe the affected horizontally-oriented blocks have wrongly maintained their original orientation.

**Expected behavior**
Horizontally-oriented blocks reorient to the new orientation.

- Place an affected horizontally-oriented block in range or within a Campanion 1.3.5 Tent.
- Pick up the Tent with the Tent Bag.
- Rotate the Tent.
- Place the Tent.
- All blocks placed reflect the new orientation.

OR

- Place an affected horizontally-oriented block in range or within a Campanion 1.3.5 Tent.
- Pick up the Tent with the Tent Bag.
- Packing the Tent skips over the affected horizontally-oriented blocks, or packing does not occur.

**Screenshots**

![image](https://user-images.githubusercontent.com/14857131/128955452-936aba4b-9b81-4ec4-b37a-0b3f13a83a3e.png)
![image](https://user-images.githubusercontent.com/14857131/128957012-fc000759-6204-45dc-844f-75e78d6d28aa.png)
![image](https://user-images.githubusercontent.com/14857131/128957115-ab5677db-5c38-4d4d-912f-b9388177ea67.png)
![image](https://user-images.githubusercontent.com/14857131/128961251-7c57035e-44de-4b63-a3bf-7e522af561ae.png)

**Logs**
(you can use https://paste.alloffabric.com)

- N/A

**Additional context**

- N/A

_**Let me know if further info is needed - Thanks!**_

**Comment by Wyn-Price** [comment]
Nothing to do with us. They should implement Block#rotate
