### ISSUE TITLE
Player can only place down a max of 64 rope ladders

### ISSUE THREAD

**Issue by Levoment** [TerraformersMC/Campanion#15]
The fix in #12 caused that rope ladders are only used from within the stack the player places. If there are still more blocks down in which ladders can be put, they are not placed if the original stack the player uses runs out. That means that the player can only put a maximum of 64 ladders down. If the height below is more than 64, no more ladder ropes are used even if the player has more rope ladders in other parts of their inventory.

I made a fix for it and I'm about to make a pull request for review.  

I don't know if it is a feature to allow the user to put down only at max 64 rope ladders such as to make it more realistic that they would have to go down and manually place more rope ladders, but if it's not, check my pull request in which the user can put down as many rope ladders at once as they have in the inventory (1, 64, or 100s).

**Comment by NeusFear** [comment]
fixed in (#22 )
