### ISSUE TITLE
Trying to connect Rope Bridge Posts in Survival vs. Creative

### ISSUE THREAD

**Issue by rapscallionism** [TerraformersMC/Campanion#150]
Whenever I attempt to build the Rope Bridges in Creative, they are solid and walkable, but when I attempt to do it in Survival, it ends up being ghost blocks. It might be in the Rope Bridge files, since there was a part identifies whether or not the player is in Creative, and if not, it says that the blocks are "ghost" or some sort like that. Not sure if that was intentional or if this is the issue, but it was just something I noticed and an issue that me and my friends encountered.

![Bridge Post Glitch](https://user-images.githubusercontent.com/87588542/135765063-ac6d78c6-6ffb-4102-a479-b4d102a8ecd0.png)

**Comment by Wyn-Price** [comment]
In survival, you need to add planks to "build" the bridge
