### ISSUE TITLE
[Feature] Add Trinkets support for backpacks

### ISSUE THREAD

**Issue by Syndaryl** [TerraformersMC/Campanion#151]
Add support for backpacks to be put in the [Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric) `chest/back` slot without dropping contents, and still be accessible via hotkey as per usual. When this option is turned on, prevent the backpack from being equipped in the usual chest slot.

Balance implications of proposed change:
* Satisfies internal logic added by Trinkets ("makes sense" to go in the backpack slot)
* Prevents wearing a second backpack trinket by filling the appropriate slot; otherwise you can equip a Campanion backpack and another backpack.
* Allows wearing armor with backpack _but_ prevents potentially wearing a buff-adding Trinket - this is probably a net buff due to customizable armor enchantments and mod-added armor sometimes being *quite* powerful, whereas there haven't been as "OP" trinkets in the community so far.

My recommendation would be to make this support configurable, defaulting to off to maintain current game balance; mod-pack curators and server admins can turn it on where desired.

Of course, I'd be turning it on immediately because it feels weird not to be able to put it in the back slot.

**Comment by Syndaryl** [comment]
One possible approach would be to have two different base items, one inheriting from chest-slot armor, and one inheriting from back-slot trinket.
Each object would implement an interface that specifies that the object wraps a "`BackpackImplementation`" object that handles the container/hotkey/dropping/contents/etc logic. Add an on-equip event that tests to see whether trinket support is enabled or not, and refuse to equip if it specifies the other type of bag.

This would stop backpacks of one type from being equipped in the "wrong" type of slot and wearing two backpacks at once.

Add a simple "craft itself" shapeless recipe to convert from one kind to the other.

**Comment by NeusFear** [comment]
This feature has been requested before. We haven't added it. Not because it's a difficult feature, but because we find that equipping a backpack needs to have some downsides as well to balance them out.

**Comment by CapoFantasma97** [comment]
> This feature has been requested before. We haven't added it. Not because it's a difficult feature, but because we find that equipping a backpack needs to have some downsides as well to balance them out.

Can't it be a config option? Not all modpacks are equal. Also, kind of a moot point when you can carry a whole warehouse worth of chests in the tent.

**Comment by Derpford** [comment]
IMO it should be up to the modpack maker whether backpacks should interfere with armor, as well as what size the inventory of each pack is. I'm fiddling with a gunpowder-fantasy dungeon crawl pack right now, and the inclusion of RelicEX has led to some serious inventory issues--since each Relic is a whole inventory slot, not only is it sensible for players to have a backpack with armor, it's also sensible for those backpacks to have quite a lot of inventory space.

**Comment by NeusFear** [comment]
Added in the 3.0.0 releases
