### ISSUE TITLE
I did some Item re textures and a Brazilian Portuguese translation

### ISSUE THREAD

**Issue by ppblitto** [TerraformersMC/Campanion#155]
Hey guys. I did some **re textures** for my personal playthrough and decided to share with you. I'm leaving attached a .zip folder with all .pngs if you want to use them in the original mod.

And I did a **PT-BR (Brazilian Portuguese)** translation file too, I'll let it attached as well.

Hope you like them!

It's been very fun to play with your mod, guys, congratulations for the excellent job!

![Showcase](https://user-images.githubusercontent.com/57157437/141105714-6ded17ff-9e8f-424c-8732-06c20fb313c3.png)

![Showcase - original sprite sizes](https://user-images.githubusercontent.com/57157437/141105708-48c55812-e550-4d5d-8b21-12cdede0c54e.png)

[Campanion Item Retextures.zip](https://github.com/TerraformersMC/Campanion/files/7512317/Campanion.Item.Retextures.zip)

[pt_br.zip](https://github.com/TerraformersMC/Campanion/files/7512314/pt_br.zip)

**Comment by NeusFear** [comment]
Those textures look great! and we would love to accept your translation. It would be much better for us if you were to create a pull request for these however

**Comment by ppblitto** [comment]
I'm sorry. At the time I made this issue I didn't know how to create a pull request! Hahaha. I'm such a noob at github...

**Comment by NeusFear** [comment]
Added in the 3.0.0 releases. Thank you so much!
