### ISSUE TITLE
Tent blocks should be immune to explosions (while not shielding the contents)

### ISSUE THREAD

**Issue by CapoFantasma97** [TerraformersMC/Campanion#156]
Currently tents are irreversibly damaged when an explosion hits them. This affects function other than looks, because the removed blocks give more space to place more stuff, but of course it doesn't look like a tent anymore.

So maybe the blocks should be immune to explosions. For balance they shouldn't be able to shield what's inside from explosions either, if possible.

**Comment by NeusFear** [comment]
Fixed in the 3.0.0 releases
