### ISSUE TITLE
Wont let me place shulker box on back with Trinket Shulker Boxes (Fabric) when i have the trinket backpack config disabled

### ISSUE THREAD

**Issue by Givoric** [TerraformersMC/Campanion#161]
Basically it wont let me put a shulker box on the trinket slot when this mod is installed. Is there a way to not let the config affect the shulker box from the other mod? i'd like to have it in a way where only the shulker box are allowed in the trinket slot, because shulker litterally attach to a surface, so to have it balanced in a way that shulker as backpack isn't useless but more of an upgrade of those backpacks.
Also if i keep the config trinket backpacks disabled the trinket shulker mod becomes completely useless because it can't be placed in the chest slot like campanion's backpacks

**Comment by Wyn-Price** [comment]
So you're saying the campanion config option is also the shuker-trinkets option?

**Comment by Givoric** [comment]
yeah, somewhat. Basically if that config option is disabled by default i can not put the shulker on the trinket slot

**Comment by Givoric** [comment]
you can try to replicate it, it only requires you to put that mod and have the default settings of campanion. Then try putting the shulker in the trinket slot

**Comment by jhbuchanan45** [comment]
I suspect I know the issue, I'll hopefully get a look at it soon

**Comment by Wyn-Price** [comment]
> I suspect I know the issue, I'll hopefully get a look at it soon

I have already solved the issue lol
