### ISSUE TITLE
Some blocks don't render in the tent preview

### ISSUE THREAD

**Issue by Wyn-Price** [TerraformersMC/Campanion#167]
![java_crGyyw4uOg](https://user-images.githubusercontent.com/15876682/164953473-8a3a99f8-6c72-48b8-b8d7-2f5a687e9d33.gif)

**Comment by Wyn-Price** [comment]
Block Entities also do not render

**Comment by Wyn-Price** [comment]
Issue arises from the cutoff alpha value for `cutout` being 0.1, and `cutout_mipped` being 0.5. 

We pass a value of 0.5, meaning the fragment gets discarded only on `cutout_mipped`
https://github.com/TerraformersMC/Campanion/blob/22856268935c64a53e8aca77e90d34f84b2c3435/src/main/java/com/terraformersmc/campanion/client/util/TentPreviewBufferBuilder.java#L16-L21

<details>
<summary>Cutout render code</summary>

```glsl
void main() {
    vec4 color = texture(Sampler0, texCoord0) * vertexColor * ColorModulator;
    if (color.a < 0.1) {
        discard;
    }
    fragColor = linear_fog(color, vertexDistance, FogStart, FogEnd, FogColor);
}
```
</details>

<details>
<summary>Cutout Mipped render code</summary>

```glsl
void main() {
    vec4 color = texture(Sampler0, texCoord0) * vertexColor * ColorModulator;
    if (color.a < 0.5) {
        discard;
    }
    fragColor = linear_fog(color, vertexDistance, FogStart, FogEnd, FogColor);
}
```
</details>

We should not be calling these shaders to render translucent objects anyway. A simple fix for this would be to force a RenderType of translucent

**Comment by jhbuchanan45** [comment]
Nice find, I'll get on that and removing that mixin now!
