### ISSUE TITLE
Rope bridge planks is not working

### ISSUE THREAD

**Issue by josemunoz18** [TerraformersMC/Campanion#184]
Mod version used: Campanion v4.1.1+fabric for 1.19.2

The rope bridge planks is not working, the recipe in REI is not working and I can't craft it.

![imagen](https://user-images.githubusercontent.com/119136771/210092859-d53d9146-1e88-4ca7-b041-b9f062480779.png)
****

**Comment by NeusFear** [comment]
Those aren't obtainable items, just right click with planks on the ghosted bridge once you connect the posts

**Comment by josemunoz18** [comment]
Thanks I will try
