### ISSUE TITLE
Balance spears

### ISSUE THREAD

**Issue by NeusFear** [TerraformersMC/Campanion#26]
Spears are currently underpowered. They do less damage than a shovel does for the same resources making them useless in melee combat. buffing mele with more damage and longer reach would be neat.

**Comment by Mantarri** [comment]
~~One other thing that would make it more useful is loyalty.~~ Nevermind, I saw that you don't plan to implement loyalty
The thing is you can get loyalty from the enchanting table on spears - it just doesn't work.

**Comment by NeusFear** [comment]
Gotcha, I'll look into that with this PR too

**Comment by Prospector** [comment]
Added in v1.0.10
