### ISSUE TITLE
key binding section in controls

### ISSUE THREAD

**Issue by Seegras** [TerraformersMC/Campanion#27]
the key-bidning is in "Gameplay". Could you move the keybinding to its own section? It shouldn't be in any of the default sections, but have its own.

**Comment by Prospector** [comment]
It makes sense to be a gameplay keybind since it's part of gameplay

**Comment by Seegras** [comment]
No other mod I know does put stuff in default minecraft sections.

**Comment by Prospector** [comment]
It's a "gameplay" category not a "vanilla minecraft" category
