### ISSUE TITLE
[MC: 1.15.2, Version: 1.0.10+build20] Latest update causes incomaptibilty with bunch o' trinkets. Crash on startup. 

### ISSUE THREAD

**Issue by lizfinite** [TerraformersMC/Campanion#28]
Hey there, 

After the most recent update, I am running into a startup crash. I've narrowed it down to bunch o' trinkets causing a conflict. 

https://pastebin.com/3LVaAbiP
This is a log with just the following:
- bunch o' trinkets 1.0.0 [(Link to curseforge page)](https://www.curseforge.com/minecraft/mc-mods/bunch-o-trinkets)
- Campanion 1.0.10
- FabricAPI 0.10.8+build310
- ModMenu 1.10.2+build32
- trinkets 2.4.2

My best guess is that the modifications you made to make spears reach further conflict with the changes bunch o trinkets makes for the builders trinket. But I could be completely wrong. 

This issue didn't occur with version 1.0.9 of campanion. If this is an issue they need to correct however, I'll create an issue there instead.

**Comment by NeusFear** [comment]
This seems like something that may need to be PRed into fapi then honestly. We can't fix it. Someone may be able to make that PR happen though so that when 1.16 is stable this conflict won't happen. This is neither theirs nor our fault.

Thanks for reporting this.

**Comment by NeusFear** [comment]
Actually now that I'm looking at it and the source of the trinkets mod linked from the curse page you posted I have no idea why there is a conflict. You might post this error there too, just in case because our method of modifying the reach distance should not be a conflict with any other mod, and I can't find where they even mixin to this.

**Comment by NeusFear** [comment]
Just kidding, we will fix this, we can just use the library that Trinkets uses.

**Comment by Wyn-Price** [comment]
Seemes to be fixed with c56bde0cbd21bee7b12d188cdb6e116fa23e80c6
