### ISSUE TITLE
Crash trying to place big tent (indoors)

### ISSUE THREAD

**Issue by calloatti** [TerraformersMC/Campanion#29]
https://paste.ee/p/NooEg

**Comment by Wyn-Price** [comment]
The paste is not found. Please paste it on a different site.

**Comment by calloatti** [comment]
oh well it expired, it was an autoupload by multimc I think they last one month. 

The crash was in 1.15.2

It was a conflict with <https://www.curseforge.com/minecraft/mc-mods/stockpile> but since stockpile is not yet on 1.16.1 I can't test again right now, closing and will test again if/when stockpile 1.16.1 is available.
