### ISSUE TITLE
Tarp Recipe Conflicts with Blockus Patterned Wool

### ISSUE THREAD

**Issue by sdaugherty** [TerraformersMC/Campanion#30]
The tarp recipe from Campanion conflicts with the patterned wool recipe in blockus, making it impossible to craft tarps or anything which requires them if Blockus is also installed.

Reported to Blockus devs here https://github.com/Brandcraf06/Blockus/issues/36

**Comment by NeusFear** [comment]
Our recipe kind of doesn't make sense anyways, I could probably change it to be a combination of shears and wool in a workbench to give you a tarp instead. We can talk about it on the team.

**Comment by NeusFear** [comment]
@Wyn-Price this was fixed in https://github.com/TerraformersMC/Campanion/commit/6aba037c8765a63af706c74c106cb5a5240db0c6 correct?

**Comment by Wyn-Price** [comment]
Yes
