### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [TerraformersMC/Campanion#31]
this is stupid forge is already good this is bad fuck you delete this shit ur fabruc sucks use forge mother fuckers fabric sucks forge is perfect awesome good for mod needs no fabric is hacks hacks HACKS mixins stupid kill your self im gay btw

**Comment by coderbot16** [comment]
Please rethink your life choices if you think that spamming modder repositories with this garbage is a valuable use of your time.
