### ISSUE TITLE
Can't See Lawn Chairs on LAN Server

### ISSUE THREAD

**Issue by queenielawrens** [TerraformersMC/Campanion#37]
I don't know why but when i place a lawn chair in my LAN world the other person can't see it.

**Comment by queenielawrens** [comment]
I'm hosting btw.  Also after testing it a bit more when they place it I can see it and sit in it

**Comment by NeusFear** [comment]
Does this problem still exist for you @queenofmillers ?

**Comment by NeusFear** [comment]
Closing due to author unresponsiveness.

**Comment by coderbot16** [comment]
Both clients need to install the mod, if your friend doesn't have the mod installed then he won't see the mod content.
