### ISSUE TITLE
compat issue between campanion and carpet

### ISSUE THREAD

**Issue by sdaugherty** [TerraformersMC/Campanion#39]
Crash log: https://paste.ee/p/Tn0b2

campanion-1.1.10+build.24
fabric-carpet-1.16-1.4.0+v200623
carpet-extra-1.16-1.4.0
fabric-api-0.14.0+build.371-1.16

minecraft 1.16.1

Crashes immediately when entering or newly generating a world.

**Comment by sdaugherty** [comment]
https://github.com/gnembon/fabric-carpet/issues/352 appears to already exist

**Comment by Wyn-Price** [comment]
This seems to be an issue with `reach-entity-attributes`, a lib which campanion uses
