### ISSUE TITLE
Inventory dump when switching between daypack and chestplate

### ISSUE THREAD

**Issue by pjlasl** [TerraformersMC/Campanion#41]
**Steps to recreate**
1. Put a daypack in the chest plate slot
2. Add inventory to the daypack
3. Replace the daypack with a chest plate (while the daypack is in the chest plate slot).

**What happens**
The daypack inventory is emptied out into the player inventory.

**What is expected**
The daypack should just get put back into the player's inventory and keep its internal inventory.

**Workaround**
Put the daypack into the player's inventory. Then add the chest plate to the slot.

I'm running the latest Fabric API and latest companion mod.

**Comment by Wyn-Price** [comment]
This is intentional. The backpacks are not meant to hold any inventory when they're outside of the chestplate slot. Changing this would essentially make them become easy to make shulker boxes, which we feel isn't very well balanced.
