### ISSUE TITLE
new version crashes server

### ISSUE THREAD

**Issue by bentterp** [TerraformersMC/Campanion#47]
https://gist.github.com/bentterp/e9d9e9bd0495c9d54a5372b31338daae

[minecraft@tux2 htv7mod]$ ls -1 mods/
Adorn-1.9.1+1.16.1.jar
RebornCore-1.16-4.3.2+build.49.jar
RoughlyEnoughItems-4.9.5.jar
SimpleBackpack_Fabric_1.16.1-1.0.24.jar
TechReborn-1.16-3.4.3+build.72.jar
better-wandering-trader-1.4.0.jar
blackstone-tools-1.0.0+1.16.1.jar
campanion-1.1.11+build.32.jar
cinderscapes-1.0.4+build.25.jar
fabric-api-0.14.1+build.372-1.16.jar
fabric-language-kotlin-1.3.71+build.1.jar
justmap-1.1.95-1.16.1-unlimited.jar
lithium-fabric-mc1.16.1-0.5.1.jar
mcf-reap-1.4.0-1.16.1.jar
mostructures-1.0.0-pre2+mc.1.16.jar
player-roles-1.0.2.jar
secretrooms-0.9.1+1.16.1.jar
sleepvote-1.8+1.16.1.jar
tdnf-mc116-1.10.90.jar
terrestria-2.0.3+build.46.jar
traverse-2.2.13+build.27.jar
[minecraft@tux2 htv7mod]$

Fabric loader is fabricloader@0.9.0+build.204

**Comment by Prospector** [comment]
Fixed in v1.1.12
