### ISSUE TITLE
Missing Recipe: Wool Tarp 

### ISSUE THREAD

**Issue by SirCaptainCaleb** [TerraformersMC/Campanion#48]
The 1.16 branch is lacking a wool tarp recipe. The recipe json file is there, but its contents have been removed.

**Comment by Wyn-Price** [comment]
The new tarp recipe is 3 wool and a pair of shears.

**Comment by SirCaptainCaleb** [comment]
It is missing in the 1.16 branch:

https://github.com/TerraformersMC/Campanion/blob/1.16/src/main/resources/data/campanion/recipes/wool_tarp.json#L1

**Comment by SirCaptainCaleb** [comment]
Oh, I see its a non-json recipe. My apologies. That's why it doesn't show up on REI

**Comment by Wyn-Price** [comment]
We can however make a REI plugin to have it show up
