### ISSUE TITLE
Wool Tarp Wiki Page is Out of Date

### ISSUE THREAD

**Issue by brenank** [TerraformersMC/Campanion#50]
The recipe for the wool tarp is out of date on the Materials page:
https://github.com/TerraformersMC/Campanion/wiki/Materials

I've created a proposed replacement image:
![wool_tarp_craft](https://user-images.githubusercontent.com/3655978/87857788-4c806800-c8de-11ea-83cf-edb71ccce70f.png)

**Comment by NeusFear** [comment]
Thanks so much! I have updated the page.
