### ISSUE TITLE
Holding a Tent Bag makes RAM usage increase until the game becomes uplayable. (When using Sodium)

### ISSUE THREAD

**Issue by calloatti** [TerraformersMC/Campanion#53]
https://paste.ee/p/GwOCi

https://youtu.be/WewKXuyO6gA

Dont know if its something that campanion or sodium needs to fix, posting only here for now.

**Comment by NeusFear** [comment]
Going to mark this as invalid until Sodium adds FRAPI support.

**Comment by NeusFear** [comment]
Fixed in 1.3.5
