### ISSUE TITLE
Incompatibility with Mo' Enchantment Mod; inadaptability to the b key of opening the backpacks

### ISSUE THREAD

**Issue by linzexin022** [TerraformersMC/Campanion#55]
Hi there, I found the Imcompatibility of spears and the mod _Mo' Enchantments_, and here's the bug report:
[crash-2020-07-24_11.41.16-client.txt](https://github.com/TerraformersMC/Campanion/files/4970192/crash-2020-07-24_11.41.16-client.txt)

By the way, it doesn't make sense logically that I press **b** to open the backpack and inventory, but I have to press **e** or **esc** to close this GUI instead of **b**. Don't know if you can make one **b** to open/close the backpack GUI?

**Comment by NeusFear** [comment]
Looks like an outdated version of MoEnchants, see Author response here: https://gitlab.com/biom4st3r/moenchantments/-/issues/30
