### ISSUE TITLE
Client crash: Rendering Block Entity

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Campanion#57]
Setup:
![image](https://user-images.githubusercontent.com/918422/88489178-118fcb80-cf93-11ea-8520-e51225f4962b.png)
Originally, the Rope Bridge post stood where the dirt block is between the fences.

Log: 
https://pastebin.com/usPZLHeb

I managed to remove the offending block with:
/setblock 19 64 -2006 minecraft:dirt destroy

**Comment by Wyn-Price** [comment]
Update to the latest campanion

**Comment by ghost** [comment]
Will do, thanks !
