### ISSUE TITLE
[Bug] No texture for the rope bridge !

### ISSUE THREAD

**Issue by timo1050** [TerraformersMC/Campanion#58]
As the title say :
![image](https://user-images.githubusercontent.com/8901731/88678153-6f84f600-d0ee-11ea-8f65-149c3fc45071.png)

**Comment by NeusFear** [comment]
You can’t have optifabric or sodium with our mod. They both disable the fabric rendering api. Sodium 0.2 will have fabric rendering api support but doesn’t as of yet.
