### ISSUE TITLE
Cannot open any backpack

### ISSUE THREAD

**Issue by Redundakitties** [TerraformersMC/Campanion#59]
Day pack, Camping pack, and Hiking pack all cannot be opened. Cannot use the keybind, cannot equip in the chest slot. 
Using most recent 1.15.2 version (1.0.11)

**Comment by NeusFear** [comment]
We're not supporting old versions, unfortunately. This takes too much time to do. We welcome PRs and we can probably push a release if someone else fixes this, but Terraformers won't fix this ourselves.
