### ISSUE TITLE
Lawn chair roads can cause weird teleportation

### ISSUE THREAD

**Issue by dranorter** [TerraformersMC/Campanion#61]
I haven't determined exactly how to duplicate this, so I'm going to give a bit more information than necessary.

I used stacked lawn chairs as a ladder and then had a nether portal on a platform on top. So I can rapidly click on each successive chair to sit in it until I'm on top, then I click on one more chair which moves me horizontally away from the ladder, and finally I press shift to exit the chair.

Sometimes, upon hitting shift to exit the final chair, I find myself teleported to the second to last chair. A more general description of the bug is that I find myself getting up from a different chair than I sat down in. If I go up the lawn chairs and then back down, I can find myself progressing in a strange order.

Once, I got down my stack of chairs and found I was unable to sit in other chairs or open chests. I could walk around but I was in an odd state where the game sort-of thought I was in a chair. So I pressed shift, and was teleported back to one of the chairs.

I've never gotten teleported from the nether to the overworld via chair, or vice versa.

**Comment by Linguardium** [comment]
I have had this issue with non-campanion ridable entities as well, to include boats. I do not believe this is a campanion issue specifically.
Normally what happens is i exit a boat, and it acts like i was not in the boat, but i cant break blocks. The client thinks i am not mounted but the server doesnt. If i attempt to dismount again, sometimes it will rubberband me back to the boat and exit properly.  I believe this may be an issue with MC proper.

**Comment by NeusFear** [comment]
Doesnt seem to happen on the latest 1.2.0 release for 1.16.2 can you test this?

**Comment by NeusFear** [comment]
Can't reproduce and no response from author
