### ISSUE TITLE
[1.16.1] Tent Item Rendering cause Crash

### ISSUE THREAD

**Issue by Yusuf8810** [TerraformersMC/Campanion#68]
In a Single-player game, when placing the tent in a tent bag in your inventory to a selected hot-bar causes game crash with the following crash report:
[crash-2020-08-19_21.13.21-client.txt](https://github.com/TerraformersMC/Campanion/files/5098765/crash-2020-08-19_21.13.21-client.txt)
The modes I use
![Annotation 2020-08-19 222053](https://user-images.githubusercontent.com/69922444/90680301-5218f700-e26a-11ea-83fa-5cb7edc4f1d1.png)

**Comment by NeusFear** [comment]
We do not support optifine or optifabric. it has incompatibilities with fabric rendering api.
