### ISSUE TITLE
Crashes when using various items

### ISSUE THREAD

**Issue by repulsivity** [TerraformersMC/Campanion#7]
I've found a few issues with items crashing the game, as well as textures not appearing.

1. After crafting a tent bag with a tent and an empty bag, the game crashes when you try to place it down.
2. Placing down two rope bridge posts in creative mode results them in having models, but having no textures on them (shown in attached screenshot)
3. Trying to create a bridge in survival results in a game crash after trying to connect two posts with rope.

It's worth noting that i have a variety of other mods installed as well, including Optifine (+ Optifabric) and Traverse, among others

Tent Bag Crash ([pastebin](https://pastebin.com/DfAq8dnG))
Rope Bridge Crash ([pastebin](https://pastebin.com/jNc5C9ai))

Untextured Posts:
![Annotation 2020-04-11 020827](https://user-images.githubusercontent.com/47663152/79005069-6e5ca700-7b99-11ea-93f2-cdee20b59efb.png)

**Comment by Wyn-Price** [comment]
All these bugs are rendering related. Does the issue occur when optifine isn't installed?

**Comment by repulsivity** [comment]
Disabling optifine works. Thanks!

**Comment by Wyn-Price** [comment]
This is still an issue, as optifine should be supported, although everything apart from the tent crash seems like possibly a fabric issue, rather than our problem

**Comment by NeusFear** [comment]
Optifabric/optifine isn't really something that as a Fabric community is supported, we suggest using Jelly squid's mods for optimizations.
