### ISSUE TITLE
Grappling hook on 1.16.2

### ISSUE THREAD

**Issue by Monster-Zer0** [TerraformersMC/Campanion#70]
Grappling hook causes crash on 1.16.2 server

I know you don't have a 1.16.2 release yet, but this might help, I don't know, but thought I would pass it along.

https://hastebin.com/tezarujapi.sql

**Comment by NeusFear** [comment]
Can you test this on 1.2.0 for 1.16.2

**Comment by NeusFear** [comment]
@Monster-Zer0 Have you had a chance to test this?

**Comment by Monster-Zer0** [comment]
Good to go. No crash. Thanks
