### ISSUE TITLE
can't place down tents, the game crashes before the schematics show up

### ISSUE THREAD

**Issue by plasticsucks** [TerraformersMC/Campanion#77]
[fabric-loader-0.9.2+build.206-1.16.1 (2020-09-03).log](https://github.com/TerraformersMC/Campanion/files/5168026/fabric-loader-0.9.2%2Bbuild.206-1.16.1.2020-09-03.log)

**Comment by plasticsucks** [comment]
I'm running this mod along with biomes you'll go mod and optifine, incase that is why the game keeps crashing, I tried in 1.16.2 but it doesn't work either.

**Comment by NeusFear** [comment]
Optifine is unsupported by any mod that leverages the fabric rendering api, which we do.
