### ISSUE TITLE
Confilcts with Carpet Mod

### ISSUE THREAD

**Issue by linzexin022** [TerraformersMC/Campanion#78]
Hi there, I found your mod conflicts with Carpet Mod.
[crash-2020-09-04_00.50.24-client.txt](https://github.com/TerraformersMC/Campanion/files/5170062/crash-2020-09-04_00.50.24-client.txt)

**Comment by NeusFear** [comment]
Correct, Carpet Mod does a number of things that conflict with a number of mods. This isn't something we can fix, it would be up to carpet to maintain greater mod compatibility.

**Comment by linzexin022** [comment]
OK, I'll report to him.
