### ISSUE TITLE
inserting the Backpack into Applied Energistics 2 storage, items it contains are duplicated.

### ISSUE THREAD

**Issue by kabiball** [TerraformersMC/Campanion#79]

**Comment by ghost** [comment]
Sorry, could you please provide more information as to how specifically the items get duplicated. Is the bag duplicated within the AE system? Are the actual stacks inside the backpack duplicated? If the bag is completely full with items does it duplicate them then? Does it duplicate the stacks themselves (like if you had two half stacks would you then have 4 half stacks) or does it duplicate the count of items (like if you have two half stacks would you then have 2 full stacks)?

**Comment by kabiball** [comment]
Put the items in Backpack and remove them from the equip slot.

item is dropped at In Creative mode, but in Survival mode it is kept

Insert the backpack into ME interface and the items the backpack contains will be dropped.
contents of backpack are kept.
Take backpack of ME interface and click on it in inventory, to drop it meny.

Mods:
  [✔️] appliedenergistics2-fabric-8.1.0-alpha.7
  [✔️] campanion-1.2.0+build.39
  [✔️] fabric-api-0.19.0+build.398-1.16
  [✔️] fabric-language-kotlin-1.3.72+build.1
  [✔️] fabriczero-0.1.4

**Comment by kabiball** [comment]
sorry, I poor write,  add gif

duplicate an all item that contains(same is due if it is filled)
![img](https://raw.githubusercontent.com/wiki/kabiball/Stack/capture_0000.gif)
