### ISSUE TITLE
Cannot place Rope Bridge at the same position

### ISSUE THREAD

**Issue by TripleKiller666** [TerraformersMC/Campanion#80]
As the Name implies, whenever i place 2 Posts on opposite directions and rightclick one of them with rope in hand.
This message appears in chat.
I dont even get wooden supports or anything, just a seethrough Block and no Ghost Blueprint from one side to another.

(Using "All of Fabric 3 Version 1.5.3")

**Comment by NeusFear** [comment]
Did you happen to add optifine or sodium to your mods list.

**Comment by TripleKiller666** [comment]
> Did you happen to add optifine or sodium to your mods list.

I have sodium in my modlist, yes

**Comment by NeusFear** [comment]
Sodium doesn’t support the fabric rendering api, if you remove it you’ll Have no issues with rendering.

**Comment by TripleKiller666** [comment]
Thanks, will do that then!
