### ISSUE TITLE
Server crashed when I threw a spear. 

### ISSUE THREAD

**Issue by oliveoiltears** [TerraformersMC/Campanion#82]
Hi! This mod seems really cool, unfortunately when I threw an iron spear the server crashed, when I restarted it and tried to reconnect it crashed the server again. Attached crash reports:
[crash-2020-09-12_16.33.05-server.txt](https://github.com/TerraformersMC/Campanion/files/5212897/crash-2020-09-12_16.33.05-server.txt)

[crash-2020-09-12_16.30.34-server.txt](https://github.com/TerraformersMC/Campanion/files/5212896/crash-2020-09-12_16.30.34-server.txt)

**Comment by NeusFear** [comment]
You're trying to use a 1.16.2 version of our mod on a 1.16.1 fabric api, this might be the issue. You could try downgrading to 1.3.1 and see if that works
