### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by shouxd** [TerraformersMC/Campanion#88]
Whenever I place a tent and look at it memory goes up to 100%, game begins to stutter and stays like that until I pick up the tent and then restart the game. Its worth to note that I have to pick up the tent otherwise if I restart and look at it again, the problem persists.

**Comment by NeusFear** [comment]
Duplicate of #53 ?

**Comment by shouxd** [comment]
Yes, sems like. Happened to me while using Sodium too

**Comment by NeusFear** [comment]
dupicate of #53
