### ISSUE TITLE
[1.15.2] Crash: rendering block entity

### ISSUE THREAD

**Issue by ponyquery** [TerraformersMC/Campanion#89]
I placed a rope bridge and upon connecting it, my game crashed. I am playing on a server with some friends and they are unable to join as well. 
Pastebin: [https://pastebin.com/piXVFp26](url) (it's marking it as NSFW for some reason)
(this is my first GitHub query, sorry if I left out something crucial)

**Comment by NeusFear** [comment]
Are you using optifine or sodium? also your pastebin link seems to be expired
