### ISSUE TITLE
Leatherworker villager Tanning Rack integration?

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Campanion#91]
This may be a bit of an invasive change, and I do not know if it can be made compatibly, so this is just an idea. Since this mod adds a proper tanning rack, I thought it could be neat for villagers to recognise the tanning rack as the workstation for the leatherworker profession in place of the cauldron when this mod is installed. Ideally, this would also mean replacing the cauldrons in all of the leatherworker buildings in villages with tanning racks.

Again, this is a change to vanilla, and may be beyond this mod's scope, but I thought it would be neat.~

**Comment by NeusFear** [comment]
That is a cool idea, but I think I agree that it may be out of scope to change the base game in this way.

**Comment by saltyseadoggo** [comment]
To be fair, you did modify wolves to be able to howl. Ow<

**Comment by NeusFear** [comment]
Wolf howling is an additive feature. It doesn't replace any functionality already present in the game
