### ISSUE TITLE
[Mod conflict] Rope bridge doesn't have texture when Sodium is loaded

### ISSUE THREAD

**Issue by K0-RR** [TerraformersMC/Campanion#92]
1.16.4, campanion 1.2.0.

**Comment by Wyn-Price** [comment]
Are you using sodium/optifine

**Comment by K0-RR** [comment]
Yes, I checked this now, and seems like it conflict with sodium.

**Comment by NeusFear** [comment]
This is a sodium issue, as they don't implement the fabric rendering api.
