### ISSUE TITLE
Issue when selecting tent bag with tent inside.

### ISSUE THREAD

**Issue by loginlogout3** [TerraformersMC/Campanion#95]
[latest.log](https://github.com/TerraformersMC/Campanion/files/5613794/latest.log)
[crash-2020-11-29_23.12.28-client.txt](https://github.com/TerraformersMC/Campanion/files/5613795/crash-2020-11-29_23.12.28-client.txt)

This was replicated in creative mode, the issue was originally had in the survival, it crashed both my and my friend's on the server game but did not crash the server. The issue is only when I pulled it out into my hand. I was playing on AOF3 modpack version 2.4.3.

**Comment by aniMattor** [comment]
I have found a similar bug when using rendering mods. When building a rope bridge, and using canvas render, the "ghosted" preview will crash MC if . If using optifabric and optifine the bridges work fine, but the tent positioning preview will crash MC. In either of these cases, If I then disable those mods, and relaunch MC the world opens up the tents/bridges work fine.

**Comment by NeusFear** [comment]
If this happens with Canvas report that to Grondag and he can fix it, the other two mods that crash it (optifabric and sodium) are not reportable to until they add FRAPI support.

**Comment by aniMattor** [comment]
Thank  you for the info. I will do that.
